// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Matrix1.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Prime")]
    public partial class PrimeFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Prime.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Prime", "\tIn order to avoid silly mistakes\r\n\tI want to be told useful facts about prime nu" +
                    "mbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Is n a prime number?")]
        [NUnit.Framework.CategoryAttribute("PrimeTest")]
        [NUnit.Framework.TestCaseAttribute("-1", "False", null)]
        [NUnit.Framework.TestCaseAttribute("1", "False", null)]
        [NUnit.Framework.TestCaseAttribute("2", "True", null)]
        [NUnit.Framework.TestCaseAttribute("3", "True", null)]
        [NUnit.Framework.TestCaseAttribute("5", "True", null)]
        [NUnit.Framework.TestCaseAttribute("7", "True", null)]
        [NUnit.Framework.TestCaseAttribute("9", "False", null)]
        [NUnit.Framework.TestCaseAttribute("11", "True", null)]
        [NUnit.Framework.TestCaseAttribute("15", "False", null)]
        [NUnit.Framework.TestCaseAttribute("17", "True", null)]
        [NUnit.Framework.TestCaseAttribute("23", "True", null)]
        [NUnit.Framework.TestCaseAttribute("25", "False", null)]
        [NUnit.Framework.TestCaseAttribute("29", "True", null)]
        [NUnit.Framework.TestCaseAttribute("32", "False", null)]
        [NUnit.Framework.TestCaseAttribute("49", "False", null)]
        [NUnit.Framework.TestCaseAttribute("77", "False", null)]
        [NUnit.Framework.TestCaseAttribute("14641", "False", null)]
        [NUnit.Framework.TestCaseAttribute("100010001", "False", null)]
        [NUnit.Framework.TestCaseAttribute("2147483647", "True", null)]
        public virtual void IsNAPrimeNumber(string p, string result, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PrimeTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Is n a prime number?", @__tags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given(string.Format("A possible prime number {0}", p), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
testRunner.When("I check for Primeality", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
testRunner.Then(string.Format("the answer will be {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
